name: firmware-stable
on:
  schedule:
    - cron:  '30 8 * * 1'
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to build from'
        required: false
        default: 'stable'
        options:
          - stable
          - master
      tg_disabled:
        type: boolean
        description: 'Disable Telegram notifications'
        required: false
        default: false
      tg_scratch:
        type: boolean
        description: 'Use TG scratch channel '
        required: false
        default: false
      graph_enabled:
        type: boolean
        description: 'Enable build time graph'
        required: false
        default: false
      teacup_only:
        type: boolean
        description: 'Only build Tea Cup profile'
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: 'Debug: Generate dummy image files'
        required: false
        default: false
      board_list:
        type: string
        description: '输入型号 (逗号分隔，如: wyze_cam3_t31x)。留空则按原逻辑编译。'
        required: false

env:
  BR2_DL_DIR: ~/dl
  FORCE_UNSAFE_CONFIGURE: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAG_NAME: firmware
  TERM: linux
  TG_TOKEN: ${{secrets.TELEGRAM_TOKEN_BOT_THINGINO}}
  TG_CHANNEL: ${{secrets.TELEGRAM_CHANNEL_THINGINO_MULTI}}
  TG_TOPIC: ${{secrets.TELEGRAM_CHANNEL_THINGINO_MULTI_TOPIC_FIRMWARE}}
  TG_CHANNEL_SCRATCH: ${{secrets.TELEGRAM_CHANNEL_THINGINO_SCRATCH}}
  TZ: UTC

jobs:
  check-updates:
    runs-on: ubuntu-24.04
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'stable' }}
          fetch-depth: 0

      - name: Check for updates
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          LATEST_RELEASE=$(gh release list --repo ${{ github.repository }} --json tagName,name | jq -r '.[] | select(.name | startswith("firmware-")) | .tagName' | head -1)
          if [[ -z "$LATEST_RELEASE" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            LATEST_RELEASE_COMMIT=$(gh api repos/${{ github.repository }}/git/ref/tags/$LATEST_RELEASE | jq -r '.object.sha')
            [[ "$(git rev-parse HEAD)" != "$LATEST_RELEASE_COMMIT" ]] && echo "should_build=true" >> $GITHUB_OUTPUT || echo "should_build=false" >> $GITHUB_OUTPUT
          fi

  prepare-release:
    runs-on: ubuntu-24.04
    needs: check-updates
    if: needs.check-updates.outputs.should_build == 'true'
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag_name }}
    steps:
      - name: Set Tag
        id: set_tag
        run: |
          T_NAME="firmware-$(TZ=UTC date +'%Y-%m-%d')"
          echo "tag_name=$T_NAME" >> $GITHUB_OUTPUT

  generate-matrix:
    runs-on: ubuntu-24.04
    needs: check-updates
    if: needs.check-updates.outputs.should_build == 'true'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'stable' }}
      - name: Generate Matrix
        id: set-matrix
        run: |
          if [[ -n "${{ github.event.inputs.board_list }}" ]]; then
            CONFIGS=$(echo "${{ github.event.inputs.board_list }}" | tr ',' '\n')
          elif [[ "${{ github.event.inputs.teacup_only }}" == 'true' ]]; then
            CONFIGS=$(find configs/cameras/ -type f -name "*defconfig" | sed 's|.*/\(.*\)_defconfig|\1|' | grep teacup)
          else
            CONFIGS=$(find configs/cameras/ -type f -name "*defconfig" | sed 's|.*/\(.*\)_defconfig|\1|')
          fi
          JSON=$(echo "$CONFIGS" | jq -R . | jq -s '{ "thingino-version": . }' -c)
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  buildroot:
    name: ${{ matrix.thingino-version }}
    needs: [generate-matrix, prepare-release]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    container:
      image: debian:trixie
    steps:
      - name: Install Tools
        run: |
          apt-get update && apt-get install -y curl gnupg2 git jq
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list
          apt-get update && apt-get install -y --no-install-recommends build-essential bc cmake cpio file gh make gawk m4 p7zip-full perl procps python3 rsync tzdata u-boot-tools unzip wget

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.event.inputs.branch || 'stable' }}
          fetch-depth: 0

      - name: Build
        run: |
          BOARD=${{ matrix.thingino-version }} make fast WORKFLOW=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: thingino-${{ matrix.thingino-version }}-firmware
          path: output-stable/${{ matrix.thingino-version }}/images/*.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare-release.outputs.tag_name }}
          files: output-stable/${{ matrix.thingino-version }}/images/*.bin
        continue-on-error: true
